language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1

script: "bundle exec rake test"

install:
  - gem install bundler
  - bundle install

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
